<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251123041725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, externalId VARCHAR(255) NOT NULL, product_name VARCHAR(255) NOT NULL, product_title VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, short_description VARCHAR(255) DEFAULT NULL, product_link VARCHAR(255) DEFAULT NULL, image_link VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, is_preorder BOOLEAN NOT NULL, category VARCHAR(255) NOT NULL, skus JSON NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, price DOUBLE PRECISION NOT NULL, sale_price DOUBLE PRECISION DEFAULT NULL, tags JSON DEFAULT NULL, is_taxable BOOLEAN NOT NULL, images JSON NOT NULL, image_default VARCHAR(255) NOT NULL, is_hazmat BOOLEAN NOT NULL, age_group VARCHAR(255) NOT NULL, sync_status JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
